### ISSUE TITLE
tensorflow-to-larod - Recognize more objects

### ISSUE THREAD

**Issue by joakimroeed** [AxisCommunications/acap3-examples#103]
I want to use the tensorflow-to-larod repo to recognize car, person but also a dag. What do I need to do to account for that? 
Is the training data set only meant for person and car?

**Comment by carlcn** [comment]
The supplied COCO training data set includes multiple objects and annotations, so you should be able to train your own model with three outputs based on that. The supplied python files (model.py, train.py and utils.py) are designed for two outputs. These has to be modified if you want to use a model with three outputs.
