### ISSUE TITLE
Storing Camera Feed To The Cloud

### ISSUE THREAD

**Issue by joakimroeed** [AxisCommunications/acap3-examples#107]
Is it possible to store the camera feed from the axis camera to the cloud. It would be very promising for someone who wish to train their own Machine Learning models. 
Help would be appreciated.

**Comment by mikaelli-axis** [comment]
There are several possibilities for this type of setup but primarily this is a matter of network setup (i.e., is the camera allowed to connect to something on another network, can the camera API be access from the cloud or is there a requirement for VPN), so at the moment we are not covering this in the ACAP SDK. If you want some inspiration for how this can be done, check out or cloud integration examples https://github.com/AxisCommunications/acap-integration-examples-aws and https://github.com/AxisCommunications/acap-integration-examples-azure
