### ISSUE TITLE
Object Detection - Output bytes for tensor

### ISSUE THREAD

**Issue by joakimroeed** [AxisCommunications/acap3-examples#108]
Where do you get the output bytes from? Why is tensor1 80 * 4, tensor2 20 * 4... etc ?
Explain where you get these values from.
```
const unsigned int FLOATSIZE = 4;
const unsigned int TENSOR1SIZE = 80 * FLOATSIZE;
const unsigned int TENSOR2SIZE = 20 * FLOATSIZE;
const unsigned int TENSOR3SIZE = 20 * FLOATSIZE;
const unsigned int TENSOR4SIZE = 1 * FLOATSIZE;
```

**Comment by carlcn** [comment]
These values must match the model used, which in this case is SSD MobileNet V2 COCO. You can find more information about the model and other examples that uses this model at https://coral.ai/models/object-detection

To be specific, the values you refer to is the size of the output vectors of this model:
80 float for up to 20 bounding boxes
20 float for up to 20 class id
20 float for up to 20 score
1 float for number of objects detected (up to 20)
