### ISSUE TITLE
Own service as ACAP application

### ISSUE THREAD

**Issue by MikDal002** [AxisCommunications/acap3-examples#113]
Hello!
I'm working on adding an MQTT broker as an ACAP application. I've built mosquitto and deployed it as a standalone application, and everything works fine with my config file. Now I would like to pack it in ACAP package, but unfortunately it doesn't work. In logs, I can only see (log comes from server report of camera)

``` 
"/usr/local/packages/mosquitto_fake/mosquitto_fake -c /usr/local/packages/mosquitto_fake/mosquitto.conf".
2021-08-27T16:07:08.949+02:00 axis-accc8ed32954 [ INFO    ] respawnd[23104]: Respawning 
``` 

During my investigation of the problem, I've changed the name of executable, because on the newest firmware (10.6) there is another process with mosquito which comes from system internals.

When I start the mosquitto from a shell, everything works well.  When the mosquitto is run by ACAP I got only "Connection refused". 

My package.conf:
```
PACKAGENAME="Broker Mosquitto"
MENUNAME='Broker Mosquitto'
APPTYPE="armv7hf"
APPNAME="mosquitto_fake"
APPID=""
LICENSENAME="Available"
LICENSEPAGE="axis"
VENDOR="Eclipse Mosquitto"
REQEMBDEVVERSION="2.0"
APPMAJORVERSION="2"
APPMINORVERSION="0"
APPMICROVERSION="11"
APPGRP="sdk"
APPUSR="sdk"
APPOPTS="-c /usr/local/packages/mosquitto_fake/mosquitto.conf"
OTHERFILES="libmosquitto.so libmosquitto.so.1 libmosquitto.so.2.0.11 mosquitto_passwd mosquitto_pub mosquitto_rr mosquitto_sub p2.txt mosquitto.conf"
SETTINGSPAGEFILE=""
SETTINGSPAGETEXT=""
VENDORHOMEPAGELINK=''
PREUPGRADESCRIPT=""
POSTINSTALLSCRIPT=""
STARTMODE="respawn"
HTTPCGIPATHS=""
```

Do you have any idea why mosquito won't be started by camera?

**Comment by desmoteo** [comment]
Try setting in package.conf

APPGRP="root"
APPUSR="root"

instead of

APPGRP="sdk"
APPUSR="sdk"

**Comment by MikDal002** [comment]
Huh, camera with 10.6 software version died :D I will have to restore it to defaults again. On camera with software 10.5 I still have service called sdkmosquitto_fake (below log about it), even after few reboots. I will have more time tomorrow to investigate it. 

```
2021-08-30T18:20:39.841+02:00 axis-accc8ed32954 [ ERR     ] systemd[15963]: sdkmosquitto_fake.service: Failed at step EXEC spawning /etc/init.d/sdkmosquitto_fake: No such file or directory
2021-08-30T18:20:39.841+02:00 axis-accc8ed32954 [ ERR     ] systemd[15963]: sdkmosquitto_fake.service: Failed to execute command: No such file or directory
```

**Comment by petterwa** [comment]
It's a good idea to try to run as root as a quick test to see if there are any permission problems as long as you sort out the permission issue and go back to sdk user.  
Mosquitto is popular and is used by AxOs system as you already discovered, but also by other ACAPs.
