### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by thuyngch** [AxisCommunications/acap3-examples#116]
Does AXIS support Python SDK so that developers can use this easy language for developing apps?
Thanks!

**Comment by petterwa** [comment]
Yes, applications written in python is an important part of the ACAP v4 release. See also #96.

**Comment by petterwa** [comment]
ACAP 4 with python support is released earlier this week. A set of python example application using ACAP4 CV SDK is available here: https://github.com/AxisCommunications/acap-computer-vision-sdk-examples
