### ISSUE TITLE
AxHttp - CORS

### ISSUE THREAD

**Issue by keesschollaart81** [AxisCommunications/acap3-examples#117]
I'm hosting some CGI endpoints using AxHTTP. I would like to be able to allow for CORS requests, coming from another host. Is there a way to enable this? I'm happy to create a POSTINSTALLSCRIPT to modify the Apache config if that is needed.

**Comment by petterwa** [comment]
Configuring CORS for apache server is more a question for the network API support channel. From ACAP application perspective you may consider  running a small http server in the ACAP, perhaps with reverse proxy config in apache so you get full freedom. axhttp is a simple, but limited cgi provider.
