### ISSUE TITLE
Inference times 

### ISSUE THREAD

**Issue by anuragkarwa001** [AxisCommunications/acap3-examples#122]
**Issue description**
When I tried to compare the inference times of  mobilenet v1ssd 300*300  on Axis Q1615 Mk 3 it is taking 15 ms and the standard given by google is for usb 3.0 edge tpu is 6.5 ms ..
why there is some much difference in the inference times 

**System setup**
- *AXIS product/device:- Q1615 Mk III*
- *Device firmware version:- 10.6*
- *SDK version:- ACAP SDK 3.3*

**Comment by joha-axis** [comment]
Hi,

You can check out some benchmarks at [Coral's Edge TPU benchmark page](https://coral.ai/docs/edgetpu/benchmarks/). On that page, the *most* similar system to an AXIS camera would be the Edge TPU-equipped ARM system, which is described as having an 11ms inference time when running a MobileNet v1 SSD model with an input resolution of 224x224, i.e., slightly lower than the one you've tested. It should also be noted that the total inference time will depend on things such as system load, hardware specifics, how the model was compiled and its exact architecture.
