### ISSUE TITLE
Help required for HTTP API (CGI endpoints)

### ISSUE THREAD

**Issue by abdullahrkw** [AxisCommunications/acap3-examples#125]
I am trying to deploy an app on axis camera `AXIS Q1798-LE `. I am trying to incorporate my cgi endpoints by trying to run given [sample](https://www.axis.com/techsup/developer_doc/acap3/3.00.0/api/axhttp/html/ax_http_serve_request_8c-example.html).
But I am having `403 Forbidden`.
Here is my manifest.json
```
{
    "schemaVersion": "1.1",
    "acapPackageConf": {
        "setup": {
            "appName": "main",
            "vendor": "vendor",
            "embeddedSdkVersion": "3.0",
            "user": {
                "username": "sdk",
                "group": "sdk"
            },
            "runMode": "respawn",
            "version": "0.0.1"
        },
        "configuration": {
            "settingPage": "index.html",
            "httpConfig": [{
                    "type": "fastCgi",
                    "name": "/test1.cgi",
                    "access": "viewer"
                },
                {
                    "type": "fastCgi",
                    "name": "/test2.cgi",
                    "access": "viewer"
                }
            ]
        }
    }
}
```
Any idea what is causing this?

**Comment by abdullahrkw** [comment]
@jojju ?

**Comment by lukgiax** [comment]
There are two problems in the manifest which causes this issue.
The first is that fastCgi is used. This is a cgi we have experimented with, but we recommend using transferCgi or reverse-proxy for acaps. The example is also written with those in mind.
The second problem is the name given to the cgi end point. The names contain a leading slash, like this: "/test1". The slash is used as part of the path, so the cgi won't be found at "test1".

Here is the original manifest entry:

```
"httpConfig": [{
                    "type": "fastCgi",
                    "name": "/test1.cgi",
                    "access": "viewer"
                },
                {
                    "type": "fastCgi",
                    "name": "/test2.cgi",
                    "access": "viewer"
                }
            ]
```

 

Here is a working entry using transferCgi instead.

```
"httpConfig": [{
                    "type": "transferCgi",
                    "name": "test1.cgi",
                    "access": "viewer"
                },
                {
                    "type": "transferCgi",
                    "name": "test2.cgi",
                    "access": "viewer"
                }
            ]
```

**Comment by abdullahrkw** [comment]
@lukgiax 
yes, I got it worked with the changes you suggested. I think you should add one application demonstrating cgi in acap examples as well.
It would definitely help.

**Comment by abdullahrkw** [comment]
@lukgiax Do you know how we receive http request body inside callback? It's being written to which input stream?
