### ISSUE TITLE
Zero copy external data to larodTensor

### ISSUE THREAD

**Issue by xsacha** [AxisCommunications/acap3-examples#126]
**Issue description**
Trying to find a way to assign input pointer rather than go via file descriptor/buffer method for creating a larodTensor.

In the examples, the buffer is used to generate the data to, so no extra copy step is required but this is uncommon in a real scenario.

**System setup**
- *AXIS product/device (e.g., Q1615 Mk III):* Q1615 Mk III
- *Device firmware version (e.g., 10.5):* 10.6
- *SDK version (e.g., ACAP SDK 3.3):* 3.3

**Example**
```C
// Setup
infInputs = larodAllocModelInputs(conn, model, 0, NULL, NULL, &error);
setupInfInputMapping(infInputs[0], &larodInputFd, &larodInputSize, &infInputBuf);

// Loop
...
    // TODO: Zero copy?
    memcpy(infInputBuf, img->data(), larodInputSize);
...
```

**Comment by carlcn** [comment]
There is currently no way to create a larodTensor by just providing a userspace pointer to the data. larod relies on passing file descriptors between processes for high efficiency. If you have input or output buffers as memory pointers then that data has to be copied into a buffer represented by a file descriptor. You can allocate the buffer from larod, then memory-map the larod-allocated fd and copy the data. Or you can create memfd, copy data to memory-mapped fd, then register the memfd to the larodTensor. If you are going to reuse this fd (for example update the data through a mmap'ed pointer) you can tell that to larod with larodTrackTensor() (see doc for this function in larod.h)

**Comment by xsacha** [comment]
Thanks
