### ISSUE TITLE
real time low latency stream with ROS 

### ISSUE THREAD

**Issue by yinwu33** [AxisCommunications/acap3-examples#127]
**Issue description**
A description of the issue you encountered or the feature you're requesting.
Hello. I'm trying to establish a vehicle platform with ROS for autonomous driving. I've successfully used  OpenCV to access the RTSP stream. But it has an unacceptable long latency (around 5 seconds).  I need a low latency real-time stream.

Is there any way that can help me access the stream? It must be c++ or python. 

Thanks!

**System setup**
- *AXIS product/device: P1375E
- *Device firmware version (e.g., 10.5):*
- *SDK version (e.g., ACAP SDK 3.3):*

**Comment by mikaelli-axis** [comment]
While this seems like a very interesting feature, the RTSP API is not a part of the ACAP platform so if you want to put forward this as a feature request you will have to use the reglar Axis support channels.
