### ISSUE TITLE
Questions: Application Example 

### ISSUE THREAD

**Issue by acschristoph** [AxisCommunications/acap3-examples#128]
Is it possible to create an example application boilerplate that covers most parts of an ACAP application in the real world?

Means:

1. Serving a Configuration Page ( and Handling parameter updating during Configuration Page/CGI) /HTTP API / Parameter API
3. Send Events (Event API)
4. Access video stream (Video capture API)

There are examples for each individual stuff but not an application boilerplate/example that covers all the parts that basically is needed in my opinion to write an ACAP application like VMD4/ObjectsAnalytics like AXIS.

thanks

**Comment by petterwa** [comment]
Our strategy so far has been to have small examples that shows how to use on or two api's. It would be good with a more complete example to speed up development time. 
Labeling this as an enhancement proposal.

**Comment by acschristoph** [comment]
Thank you, sounds good.
