### ISSUE TITLE
TFLITE version used by larod 2.2

### ISSUE THREAD

**Issue by gj-raza** [AxisCommunications/acap3-examples#130]
**Issue description**
We're developing an application with a custom model  and when the app runs, it gives an error:  

 Unable to run inference on model /usr/local/packages/XXXXXXXX/model/XXXXXXXXX.tflite: Asynchronous connection has been closed (-6)

We suspect that this error is because of an unsupported layer in TF Lite. Can you please, inform us which version of  TF Lite, larod is using ?

**System setup**
- AXIS product/device : Q1798-LE
- Device firmware version : 10.6
- SDK version :  ACAP SDK 3.4

**Logs**
Unable to run inference on model /usr/local/packages/XXXXXXXX/model/XXXXXXXXX.tflite: Asynchronous connection has been closed (-6)

**Comment by carlcn** [comment]
Larod in firmware 10.6 is using TF lite version 2.3.1
Please find more information on how to use larod [here](https://www.axis.com/techsup/developer_doc/acap3/3.4/api/larod/html/md__opt_builder-doc_larod_doc_introduction-for-app-developers.html).
