### ISSUE TITLE
axoverlay_redraw +  AXOVERLAY_COLORSPACE_ARGB32 slower than expected

### ISSUE THREAD

**Issue by eccrow** [AxisCommunications/acap3-examples#138]
**Issue description**
 axoverlay_redraw(&error) blocks for 80-100ms when the palette is set to AXOVERLAY_COLORSPACE_ARGB32, is that expected?. When the palette is set to AXOVERLAY_COLORSPACE_4BIT_PALETTE blocking is minimal.

**System setup**
- *AXIS product/device (e.g., Q1615 Mk III):*
- *Device firmware version (e.g., 10.6):*
- *SDK version (e.g., ACAP SDK 3.4):*

**Comment by pataxis** [comment]
What system setup did you have, i.e. which SDK, product and firmware did you use?

**Comment by EarthCam** [comment]
I am working on a Q1615 Mk III, running firmware 10.6 and  I am using ACAP 3.4.

axoverlay_redraw just seems sluggish when AXOVERLAY_COLORSPACE_ARGB32 is set.
Alternatively we would like to try out  the OPENGLES backend but there is no example.

**Comment by pataxis** [comment]
The team has not been able to reproduce this on 10.8.
