### ISSUE TITLE
edge tpu runtime version for  Q1615 Mk III, os: 10.8.1

### ISSUE THREAD

**Issue by gj-raza** [AxisCommunications/acap3-examples#147]
## Issue description

I wanted to confirm what is the version of edge tpu runtime for the following device setup so that we can build our models accordingly. Thanks 

## System setup
- *AXIS product/device :  Q1615 Mk III
- *Device firmware version : 10.8.1
- *SDK version :  ACAP SDK 3.4

## Logs

N/A

**Comment by carlcn** [comment]
Edge TPU compiler version 16.0 and runtime version 14 now supported
    
Google Edge TPU compiler version 16 was recently released (https://coral.ai/news/updates-07-2021). This released was accompanied with a new runtime version 14 as well (https://coral.ai/docs/edgetpu/compiler/#compiler-and-runtime-versions). larod version 3.0.21 in our firmware now supports it!

Device firmware 10.8.1 uses larod version 3.0.33
