### ISSUE TITLE
SDK 3.1 is missing yet firmware 9.8 only supports SDK 3.1 

### ISSUE THREAD

**Issue by mms-** [AxisCommunications/acap3-examples#173]
No 3.0 or 3.1 SDK here : https://hub.docker.com/r/axisecp/acap-sdk/tags?page=1

Yet many cameras stuck on 9.8 firmware can't run anything past 3.1. How to target these cameras with ACAP 3?

What am I missing?

**Comment by pataxis** [comment]
Hi @mms- and thanks for reaching out. In our GitHub organization discussion we have a [question](https://github.com/orgs/AxisCommunications/discussions/29) that we are working on and which will answer your question.
