### ISSUE TITLE
how can i use the vdo APIs to set properties( width, heigh, frame-rate ) for rtsp on axis web

### ISSUE THREAD

**Issue by vuhailongkl97** [AxisCommunications/acap3-examples#200]
## Issue description
How can i use the vdo APIs to set properties( width, heigh, frame-rate ) for rtsp on axis's web
## System setup

- *AXIS product/device (e.g., Q1615 Mk III): Q1615 Mk III
- *Device firmware version (e.g., 10.5): 11.3
- *SDK version (e.g., ACAP SDK 3.3): SDK 3.3

**Comment by pataxis** [comment]
Hi @vuhailongkl97  thanks for reaching out,

in this repository the VDO API is provided as `.so` file for use in C/C++ applications. 

This question is a bit out of scope for this repository, but you can search for previous asked RTSP questions in [AxisCommunications Discussions](https://github.com/orgs/AxisCommunications/discussions) and if you don't find a suitable Q/A there ask a new one.

Finally I did see that there is some documentation for [Video Streaming over RTSP](https://www.axis.com/vapix-library/subjects/t10175981/section/t10051110/display?section=t10051110-t10003610) in VAPIX that might be interesting for you.
