### ISSUE TITLE
How to Set ACAP Application to Start by Default on Axis Camera?

### ISSUE THREAD

**Issue by ayoubnaitchrif** [AxisCommunications/acap3-examples#224]
## Issue description

Hello,

I have developed an application for Axis cameras using the Axis Camera Application Platform (ACAP) and created a Docker-based build. I have successfully uploaded the .eap file to the camera system, but I am encountering issues with making the application start by default when the camera boots up.

As the camera is installed on an autonomous robot for our clients, we cannot start it manually each time, so I am wondering how I can set it to start by default, or at least once it launched it will relaunch automatically after reboot (same behavior of the default apps)

Thanks.

## System setup

-AXIS Q6225-LE PTZ Camera
-Device firmware version: 11.8.61
-ACAP SDK 3.3

**Comment by pataxis** [comment]
Depending on if you use manifest.json or the old package.conf (not recommended) format, you can see options in [this table](https://axiscommunications.github.io/acap-documentation/docs/acap-sdk-version-3/develop-applications/application-project-structure.html#manifest-file-content) in the ACAP documentation.

In manifest.json it's called `acapPackageConf.setup.runMode` and in package.conf `STARTMODE`. The value for your use case sounds like it should be `respawn`.

**Comment by ayoubnaitchrif** [comment]
Thanks
