### ISSUE TITLE
Custom MQTT message from ACAP3 application

### ISSUE THREAD

**Issue by PierrickTenevia** [AxisCommunications/acap3-examples#227]
## Issue description
Hello,

We are looking to send MQTT messages using the Axis MQTT publisher, which is already implemented by Axis in the camera. While it is possible to send MQTT messages using ONVIF stateless events, we are unable to fully customize the topic or the content of the frames. For instance, the topic is prefixed with "onvif:CameraApplicationPlatform/axis:".

Is there a way to customize these frames? I couldn't find any information in the Vapix API regarding the ability to publish an MQTT message.

Thank you,
Pierrick Thévenet

## System setup

- *AXIS product/device : P1468-LE *
- *Device firmware version : 11.11.109*
- *SDK version : ACAP SDK 3.5*

## Logs
-

**Comment by pataxis** [comment]
Hi @PierrickTenevia , MQTT is not a supported API in ACAP version 3 SDK (nor in the newer ACAP Native SDK) and is therefore out of scope in this repository.

You could have a look at the VAPIX documentation and the [MQTT](https://developer.axis.com/analytics/axis-object-analytics-counting-data#mqtt) section.
You could also search the larger AxisCommunications [Discussions](https://github.com/orgs/AxisCommunications/discussions) if a similar question has been brought up before.
