### ISSUE TITLE
How to access the frames from each video stream?

### ISSUE THREAD

**Issue by huysc0ville** [AxisCommunications/acap3-examples#64]
We would like to build an application which reads the video streams from a P7304 4-channel encoder so we can pass it to AWS Kinesis Producer C SDK (https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/master/samples/KvsVideoOnlyStreamingSample.c).
 Sorry if this is a foolish question, as we are not yet very familiar with the ACAP SDK.
We see that there is a a sample application that looks very relevant; https://github.com/AxisCommunications/acap3-examples/tree/master/vdostream , but as there are several streams available on this encoder, please could you advice us how to select a given stream? "

**Comment by johan-bjareholt** [comment]
If you take a look at the most recent version of the ACAP3 documentation, multiple setting options for new streams are listed and one of them is "channel" which represent different video channels such as overview and each respective video input.
https://www.axis.com/techsup/developer_doc/acap3/3.2/api/vdostream/html/vdo-stream_8h.html

This can then in turn be applied in the same way as for example "format" is used in the example when starting a new stream.

Does that answer your question?
