### ISSUE TITLE
Web UI notification

### ISSUE THREAD

**Issue by ilsme** [AxisCommunications/acap3-examples#90]
Hi,

I'm wondering if there is an API to show the ACAP app's custom notifications for the user on the Web UI?

There are standard notifications like below but I didn't find a way to reuse them for custom notifications of my application.
![image](https://user-images.githubusercontent.com/37020050/119493188-25aa8200-bd8a-11eb-8316-3f39f387c22f.png)

Thanks.

**Comment by mikaelli-axis** [comment]
This is not something we are currently supporting. The camera WebUI is somewhat limited in scope and focused around installation and initial configuration of the device. Commonly ACAPs include their own UI where these types of notifications can be displayed, alternatively rely on the event framework for sending notifications. Check the ACAP developer pages for more information on how to include configuration UI for your ACAP.

**Comment by ilsme** [comment]
Got it, thanks.
