### ISSUE TITLE
AxEvents > Companion App

### ISSUE THREAD

**Issue by keesschollaart81** [AxisCommunications/acap3-examples#92]
I see the Axis companion app can react to both VMD and Axis Object Analytics events. Is there a way for 3th party developers to raise their own events that can be consumed in this app? Would be great to utilize this push notification feature of it.

If not, can I push a event/message to either the VMD or the AOA topic?

![image](https://user-images.githubusercontent.com/6755359/120447826-42971480-c38b-11eb-9a18-f0444772e625.png)

**Comment by mikaelli-axis** [comment]
You can define and publish events from your application using the axEvent API, but questions about what is possible with the Companion application is beyond what we can answer here. I would recommend contacting Axis customer support regarding how to configure the companion application to listen to custom application events.

**Comment by keesschollaart81** [comment]
Will do! If I get a solution back, I'll report here.
